name: Dicker Series Builds

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login 
    - name: Build and push
      
      run: heroku container:push web -a ${{ secrets.HEROKU_APP_NAME }}
    - name: Release
      
      run: heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
        
        

      
