name: Deploy

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main


jobs:
  
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jurimetry/jurimetry.drivers
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "drivers-jurimetry-data"
          heroku_email: "rwspatin@gmail.com"
          usedocker: true
        
        

      
